<?php
include "framework/database/connect-cloud.php";

//Mengambil configurasi tanggal payroll bedasarkan tanggal kemarin
$query = "SELECT PAY_CONFIG_NBR, PAY_BEG_DTE, PAY_END_DTE FROM PAY.PAY_CONFIG_DTE WHERE PAY_CONFIG_NBR = 43";
//$query = "SELECT PAY_CONFIG_NBR, PAY_BEG_DTE, PAY_END_DTE FROM PAY.PAY_CONFIG_DTE WHERE PAY_BEG_DTE <= CURRENT_DATE AND PAY_END_DTE >= CURRENT_DATE";
$result = mysql_query($query,$local);
$row    = mysql_fetch_array($result);
$PayConfigNbr = $row['PAY_CONFIG_NBR'];
$PayBegDte    = $row['PAY_BEG_DTE'];
$PayEndDte    = $row['PAY_END_DTE'];

//Untuk menghapus data CDW yang memiliki PAY_CONFIG_NBR hari kemarin
$query  = "DELETE FROM $CDW.MKG_BNS WHERE PRN_CO_NBR = ". $CoNbrDef ." AND PAY_CONFIG_NBR = ".$PayConfigNbr;
//$result=mysql_query($query,$cloud);
//$query=str_replace($CDW,"CDW",$query);
$result=mysql_query($query,$local);

$query = "SELECT
	PYMT.PYMT_NBR,
	HED.ORD_NBR,
	HED.ORD_TS,
	HED.REF_NBR,
	HED.ORD_TTL,
	HED.ORD_STT_ID,
	STT.ORD_STT_DESC,
	COM.ACCT_EXEC_NBR,
	HED.BUY_CO_NBR,
	COM.NAME AS BUY_CO_NAME,
	DATE(HED.DUE_TS)AS DUE_DTE,
	BLJRN.BILL_DTE,
	HED.PRN_CO_NBR,
	COM.NAME AS PRN_CO_NAME,
	HED.TOT_AMT,
	HED.TOT_REM,
	PYMT.PYMT_TYP,
	PYMT.TND_AMT,
	PYMT.BNK_CO_NBR,
	PYMT.VAL_NBR,
	CASE
		WHEN
			DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY))
			THEN 0
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY),INTERVAL 30 DAY))
			THEN 20
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 60 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 60 DAY),INTERVAL 30 DAY))
			THEN 40
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 90 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 90 DAY),INTERVAL 30 DAY))
			THEN 60
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY),INTERVAL 30 DAY))
			THEN 80
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY))
			THEN 100
	END AS DEPN_PCT,
	CASE
		WHEN
			DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY))
			THEN ((PYMT.TND_AMT  * 1)/100) * (100 / 100)
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY),INTERVAL 30 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (20 / 100))
		WHEN
			DATE(PYMT.CRT_TS) >  (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 60 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 60 DAY),INTERVAL 30 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (40 / 100))
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 90 DAY))
			AND DATE(BLJRN.BILL_DTE) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 90 DAY),INTERVAL 30 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (60 / 100))
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY),INTERVAL 30 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (80 / 100))
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (0 / 100))
	END AS BNS_AMT,
	PYMT.CRT_NBR,
	PYMT.CRT_TS,
	0 AS UPD_NBR,
	CURRENT_TIMESTAMP AS UPD_TS,
	'".$PayConfigNbr."' AS PAY_CONFIG_NBR,
	0 AS ACT_F
FROM CMP.PRN_DIG_ORD_PYMT PYMT
	INNER JOIN CMP.PRN_DIG_ORD_HEAD HED ON PYMT.ORD_NBR = HED.ORD_NBR
	INNER JOIN CMP.PRN_DIG_STT STT ON HED.ORD_STT_ID = STT.ORD_STT_ID
	INNER JOIN CMP.COMPANY COM ON HED.BUY_CO_NBR = COM.CO_NBR
	INNER JOIN(
		SELECT
			 ORD_NBR,
			DATE( MIN(CRT_TS)) AS BILL_DTE
	   FROM CMP.JRN_PRN_DIG
	   WHERE ORD_STT_ID = ('BL')
	   GROUP BY ORD_NBR
	)BLJRN ON PYMT.ORD_NBR = BLJRN.ORD_NBR
	INNER JOIN(
		SELECT
			 ORD_NBR,
			 DATE(MIN(CRT_TS)) AS CP_DTE
	   FROM CMP.JRN_PRN_DIG
	   WHERE ORD_STT_ID = ('CP')
	   GROUP BY ORD_NBR
	)CPJRN ON PYMT.ORD_NBR = CPJRN.ORD_NBR
WHERE PYMT.DEL_NBR=0
	AND PYMT.VAL_NBR !=0
	AND HED.DEL_NBR  =0
	AND DATE(CPJRN.CP_DTE) >= '$PayBegDte' 
	AND DATE(CPJRN.CP_DTE) <= '$PayEndDte'
	AND HED.ORD_STT_ID = 'CP'
	AND COM.ACCT_EXEC_NBR !=0
GROUP BY PYMT.PYMT_NBR";
echo "<pre>".$query."<br/><br/>";
$results = mysql_query($query, $local);
while($row  = mysql_fetch_array($results)){
	$sql = "INSERT INTO $CDW.MKG_BNS(
		PYMT_NBR,
		ORD_NBR,
		ORD_TS,
		REF_NBR,
		ORD_TTL,
		ORD_STT_ID,
		ORD_STT_DESC,
		ACCT_EXEC_NBR,
		BUY_CO_NBR,
		BUY_CO_NAME,
		DUE_DTE,
		BILL_DTE,
		PRN_CO_NBR,
		PRN_CO_NAME,
		TOT_AMT,
		TOT_REM,
		PYMT_TYP,
		TND_AMT,
		BNK_CO_NBR,
		VAL_NBR,
		DEPN_PCT,
		BNS_AMT,
		CRT_NBR,
		CRT_TS,
		UPD_NBR,
		UPD_TS,
		PAY_CONFIG_NBR,
		ACT_F
	)VALUES (
		'".$row['PYMT_NBR']."',
		'".$row['ORD_NBR']."',
		'".$row['ORD_TS']."',
		'".$row['REF_NBR']."',
		'".$row['ORD_TTL']."', 
		'".$row['ORD_STT_ID']."', 
		'".$row['ORD_STT_DESC']."',
		'".$row['ACCT_EXEC_NBR']."',
		'".$row['BUY_CO_NBR']."',
		'".$row['BUY_CO_NAME']."',
		'".$row['DUE_DTE']."',
		'".$row['BILL_DTE']."',
		'".$row['PRN_CO_NBR']."',
		'".$row['PRN_CO_NAME']."',
		'".$row['TOT_AMT']."',
		'".$row['TOT_REM']."',
		'".$row['PYMT_TYP']."',
		'".$row['TND_AMT']."',
		'".$row['BNK_CO_NBR']."',
		'".$row['VAL_NBR']."',
		'".$row['DEPN_PCT']."',
		'".$row['BNS_AMT']."',
		'".$row['CRT_NBR']."',
		'".$row['CRT_TS']."',
		'".$row['UPD_NBR']."',
		'".$row['UPD_TS']."',
		'".$row['PAY_CONFIG_NBR']."',
		'".$row['ACT_F']."'		
	)";
	//echo $sql."<br><br>";
	//$result = mysql_query($sql,$cloud);
	//$sql 	= str_replace($CDW,"CDW",$sql);
	$result = mysql_query($sql,$local);
}
?>