<?php
include "framework/database/connect.php";

$searchQuery    = strtoupper($_REQUEST['s']);
$group 			= $_GET['GROUP'];
$whereClauses    = array("PYMT.DEL_NBR=0","PYMT.VAL_NBR !=0","HED.DEL_NBR  =0","HED.ORD_STT_ID = 'CP'","COM.ACCT_EXEC_NBR !=0");

if ($_GET['PAY_CONFIG_NBR'] != ""){
	$whereClauses[] = "PAY_CONFIG_NBR = '" . $_GET['PAY_CONFIG_NBR'] . "'";
	$PayConfigNbr 	= $_GET['PAY_CONFIG_NBR'];
}

if ($_GET['PAY_BEG_DTE'] != ""){
	$whereClauses[] = "DATE(CPJRN.CP_DTE) = '" . $_GET['PAY_BEG_DTE'] . "'";
}

if ($_GET['PAY_END_DTE'] != ""){
	$whereClauses[] = "DATE(CPJRN.CP_DTE) = '" . $_GET['PAY_END_DTE'] . "'";
}

switch (strtoupper($group)) {
	case "BUY_CO_NBR":
		$groupClause = "BUY_CO_NBR";
		break;
	case "PYMT_NBR":
	default:
		$groupClause = "PYMT_NBR";
		break;
}

$whereClauses = implode(" AND ", $whereClauses);

$query = "SELECT
	PYMT.PYMT_NBR,
	HED.ORD_NBR,
	HED.ORD_TS,
	HED.REF_NBR,
	HED.ORD_TTL,
	HED.ORD_STT_ID,
	STT.ORD_STT_DESC,
	COM.ACCT_EXEC_NBR,
	HED.BUY_CO_NBR,
	COM.NAME AS BUY_CO_NAME,
	DATE(HED.DUE_TS)AS DUE_DTE,
	BLJRN.BILL_DTE,
	HED.PRN_CO_NBR,
	COM.NAME AS PRN_CO_NAME,
	HED.TOT_AMT,
	HED.TOT_REM,
	PYMT.PYMT_TYP,
	PYMT.TND_AMT,
	PYMT.BNK_CO_NBR,
	PYMT.VAL_NBR,
	CASE
		WHEN
			DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY))
			THEN 0
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY),INTERVAL 30 DAY))
			THEN 20
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 60 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 60 DAY),INTERVAL 30 DAY))
			THEN 40
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 90 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 90 DAY),INTERVAL 30 DAY))
			THEN 60
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY),INTERVAL 30 DAY))
			THEN 80
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY))
			THEN 100
	END AS DEPN_PCT,
	CASE
		WHEN
			DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY))
			THEN ((PYMT.TND_AMT  * 1)/100) * (100 / 100)
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 30 DAY),INTERVAL 30 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (20 / 100))
		WHEN
			DATE(PYMT.CRT_TS) >  (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 60 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 60 DAY),INTERVAL 30 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (40 / 100))
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 90 DAY))
			AND DATE(BLJRN.BILL_DTE) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 90 DAY),INTERVAL 30 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (60 / 100))
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY))
			AND DATE(PYMT.CRT_TS) <= (DATE_ADD(DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY),INTERVAL 30 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (80 / 100))
		WHEN
			DATE(PYMT.CRT_TS) > (DATE_ADD(DATE(BLJRN.BILL_DTE), INTERVAL COALESCE(COM.PAY_TERM,0) + 120 DAY))
			THEN (((PYMT.TND_AMT  * 1)/100) - ((PYMT.TND_AMT  * 1)/100) * (0 / 100))
	END AS BNS_AMT,
	PYMT.CRT_NBR,
	PYMT.CRT_TS,
	0 AS UPD_NBR,
	CURRENT_TIMESTAMP AS UPD_TS,
	'".$PayConfigNbr."' AS PAY_CONFIG_NBR,
	0 AS ACT_F
FROM CMP.PRN_DIG_ORD_PYMT PYMT
	INNER JOIN CMP.PRN_DIG_ORD_HEAD HED ON PYMT.ORD_NBR = HED.ORD_NBR
	INNER JOIN CMP.PRN_DIG_STT STT ON HED.ORD_STT_ID = STT.ORD_STT_ID
	INNER JOIN CMP.COMPANY COM ON HED.BUY_CO_NBR = COM.CO_NBR
	INNER JOIN(
		SELECT
			 ORD_NBR,
			DATE( MIN(CRT_TS)) AS BILL_DTE
	   FROM CMP.JRN_PRN_DIG
	   WHERE ORD_STT_ID = ('BL')
	   GROUP BY ORD_NBR
	)BLJRN ON PYMT.ORD_NBR = BLJRN.ORD_NBR
	INNER JOIN(
		SELECT
			 ORD_NBR,
			 DATE(MIN(CRT_TS)) AS CP_DTE
	   FROM CMP.JRN_PRN_DIG
	   WHERE ORD_STT_ID = ('CP')
	   GROUP BY ORD_NBR
	)CPJRN ON PYMT.ORD_NBR = CPJRN.ORD_NBR
WHERE ".$whereClauses." 
GROUP BY ".$groupClause."";

echo "<pre>".$query;

$results = array(
	'parameter' => $_GET,
	'data' => array()
);

$result = mysql_query($query);
while($row = mysql_fetch_assoc($result)) {
	$results['data'][] = $row;
	
	$results['total']['TOT_AMT']		+= $row['TOT_AMT'];
	$results['total']['TOT_REM']		+= $row['TOT_REM'];
	$results['total']['TND_AMT']		+= $row['TND_AMT'];
	$results['total']['TND_AMT_APV']	+= $row['TND_AMT_APV'];
	$results['total']['TND_AMT_NAPV']	+= $row['TND_AMT_NAPV'];
	$results['total']['BNS_AMT']		+= $row['BNS_AMT'];
	$results['total']['BNS_AMT_APV']	+= $row['BNS_AMT_APV'];
	$results['total']['BNS_AMT_NAPV']	+= $row['BNS_AMT_NAPV'];
}

echo json_encode($results);
?>