<?php
    include "framework/database/connect.php";
	include "framework/functions/default.php";
    include "framework/functions/crypt.php";
    include "framework/functions/print-digital.php";

	$QueryParam = "SELECT VAL_R2S, VAL_R2P FROM NST.PARAM_LOC PLC";
	$ResultParam= mysql_query($QueryParam);
	$rowParam   = mysql_fetch_array($ResultParam);
	$R2S		= $rowParam['VAL_R2S'];
	$R2P		= $rowParam['VAL_R2P'];

    $query="SELECT
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='FLJ320P' THEN ORD_Q*PRN_WID*PRN_LEN ELSE 0 END),0) AS FLJ320P,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='KMC6501' THEN ORD_Q ELSE 0 END),0) AS KMC6501,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='RVS640' THEN ORD_Q*PRN_LEN*PRN_WID ELSE 0 END),0) AS RVS640,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='AJ1800F' THEN ORD_Q*PRN_LEN*PRN_WID ELSE 0 END),0) AS AJ1800F,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='MVJ1624' THEN ORD_Q*PRN_LEN*PRN_WID ELSE 0 END),0) AS MVJ1624,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='KMC8000' THEN ORD_Q ELSE 0 END),0) AS KMC8000,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='KMC1085' THEN ORD_Q ELSE 0 END),0) AS KMC1085,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='KMC8000' THEN ORD_Q*".$R2S." ELSE 0 END),0) AS KMC8000_NETT,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='KMC1085' THEN ORD_Q* ".$R2P." ELSE 0 END),0) AS KMC1085_NETT,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='HPL375' THEN ORD_Q*PRN_LEN*PRN_WID ELSE 0 END),0) AS HPL375,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='SGH6090' THEN ORD_Q*PRN_LEN*PRN_WID ELSE 0 END),0) AS SGH6090,
		COALESCE(SUM(CASE WHEN PRN_DIG_EQP='LQ1390' THEN ORD_Q*PRN_LEN*PRN_WID ELSE 0 END),0) AS LQ1390
	FROM CMP.PRN_DIG_ORD_DET DET 
		INNER JOIN CMP.PRN_DIG_ORD_HEAD HED ON DET.ORD_NBR=HED.ORD_NBR 
		INNER JOIN CMP.PRN_DIG_TYP TYP ON DET.PRN_DIG_TYP=TYP.PRN_DIG_TYP 
	WHERE DATE(ORD_TS)=CURRENT_DATE AND HED.DEL_NBR=0 AND DET.DEL_NBR=0 AND DET.PRN_DIG_TYP !='PROD'";
    $resultp=mysql_query($query);
	$rowp=mysql_fetch_array($resultp);
    //echo $query;
    $query="SELECT 
		SUM(PRN_FLJ320P) AS PRN_FLJ320P, SUM(FIN_FLJ320P) AS FIN_FLJ320P, SUM(RDY_FLJ320P) AS RDY_FLJ320P,
		SUM(PRN_KMC6501) AS PRN_KMC6501, SUM(FIN_KMC6501) AS FIN_KMC6501, SUM(RDY_KMC6501) AS RDY_KMC6501,
		SUM(PRN_RVS640) AS PRN_RVS640, SUM(FIN_RVS640) AS FIN_RVS640, SUM(RDY_RVS640) AS RDY_RVS640,
		SUM(PRN_AJ1800F) AS PRN_AJ1800F, SUM(FIN_AJ1800F) AS FIN_AJ1800F, SUM(RDY_AJ1800F) AS RDY_AJ1800F,
		SUM(PRN_MVJ1624) AS PRN_MVJ1624, SUM(FIN_MVJ1624) AS FIN_MVJ1624, SUM(RDY_MVJ1624) AS RDY_MVJ1624,
		SUM(PRN_HPL375) AS PRN_HPL375, SUM(FIN_HPL375) AS FIN_HPL375, SUM(RDY_HPL375) AS RDY_HPL375,
		SUM(PRN_SGH6090) AS PRN_SGH6090, SUM(FIN_SGH6090) AS FIN_SGH6090, SUM(RDY_SGH6090) AS RDY_SGH6090,
		SUM(PRN_LQ1390) AS PRN_LQ1390, SUM(FIN_LQ1390) AS FIN_LQ1390, SUM(RDY_LQ1390) AS RDY_LQ1390
	FROM(
		SELECT 
			DTE, 
			SUM(PRN_FLJ320P) AS PRN_FLJ320P, SUM(FIN_FLJ320P) AS FIN_FLJ320P, SUM(RDY_FLJ320P) AS RDY_FLJ320P,
			SUM(PRN_KMC6501)+SUM(PRN_KMC8000)+SUM(PRN_KMC1085) AS PRN_KMC6501, 
			SUM(FIN_KMC6501)+SUM(FIN_KMC8000)+SUM(FIN_KMC1085) AS FIN_KMC6501 ,
			SUM(RDY_KMC6501)+SUM(RDY_KMC8000)+SUM(RDY_KMC1085) AS RDY_KMC6501,
			SUM(PRN_RVS640) AS PRN_RVS640, SUM(FIN_RVS640) AS FIN_RVS640, SUM(RDY_RVS640) AS RDY_RVS640,
			SUM(PRN_AJ1800F) AS PRN_AJ1800F, SUM(FIN_AJ1800F) AS FIN_AJ1800F, SUM(RDY_AJ1800F) AS RDY_AJ1800F,
			SUM(PRN_MVJ1624) AS PRN_MVJ1624, SUM(FIN_MVJ1624) AS FIN_MVJ1624, SUM(RDY_MVJ1624) AS RDY_MVJ1624,
			SUM(PRN_HPL375) AS PRN_HPL375, SUM(FIN_HPL375) AS FIN_HPL375, SUM(RDY_HPL375) AS RDY_HPL375,
			SUM(PRN_SGH6090) AS PRN_SGH6090, SUM(FIN_SGH6090) AS FIN_SGH6090, SUM(RDY_SGH6090) AS RDY_SGH6090,
			SUM(PRN_LQ1390) AS PRN_LQ1390, SUM(FIN_LQ1390) AS FIN_LQ1390, SUM(RDY_LQ1390) AS RDY_LQ1390
		FROM CDW.PRN_DIG_PROD
		WHERE DTE < CURRENT_DATE

		UNION ALL

		SELECT ORD_TS,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='FLJ320P' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q != ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(PRN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS PRN_FLJ320P,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='FLJ320P' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q = ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(FIN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS FIN_FLJ320P,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='FLJ320P' AND ORD_STT_ID IN ('QU','PR','FN','RD') AND ORD_STT_ID NOT IN ('CP') AND ((PRN_CMP_Q=ORD_Q AND FIN_CMP_Q=ORD_Q) OR (ORD_STT_ID = 'RD')) 
				THEN ROUND(ORD_Q*PRN_WID*PRN_LEN) ELSE 0 END),0) AS RDY_FLJ320P,
									
			
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP IN ('KMC6501', 'KMC8000', 'KMC1085') AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q != ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ORD_Q - PRN_CMP_Q) ELSE 0 END),0) AS PRN_KMC6501,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP IN ('KMC6501', 'KMC8000', 'KMC1085') AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q = ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ORD_Q - FIN_CMP_Q) ELSE 0 END),0) AS FIN_KMC6501,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP IN ('KMC6501', 'KMC8000', 'KMC1085') AND ORD_STT_ID IN ('QU','PR','FN','RD') AND ORD_STT_ID NOT IN ('CP') AND ((PRN_CMP_Q=ORD_Q AND FIN_CMP_Q=ORD_Q) OR (ORD_STT_ID = 'RD')) THEN ORD_Q ELSE 0 END),0) AS RDY_KMC6501,
			
			
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='RVS640' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q != ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(PRN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS PRN_RVS640,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='RVS640' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q = ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(FIN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS FIN_RVS640,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='RVS640' AND ORD_STT_ID IN ('QU','PR','FN','RD') AND ORD_STT_ID NOT IN ('CP') AND ((PRN_CMP_Q=ORD_Q AND FIN_CMP_Q=ORD_Q) OR (ORD_STT_ID = 'RD')) 
				THEN ROUND(ORD_Q*PRN_WID*PRN_LEN) ELSE 0 END),0) AS RDY_RVS640,
				
			
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='AJ1800F' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q != ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(PRN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS PRN_AJ1800F,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='AJ1800F' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q = ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(FIN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS FIN_AJ1800F,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='AJ1800F' AND ORD_STT_ID IN ('QU','PR','FN','RD') AND ORD_STT_ID NOT IN ('CP') AND ((PRN_CMP_Q=ORD_Q AND FIN_CMP_Q=ORD_Q) OR (ORD_STT_ID = 'RD')) 
				THEN ROUND(ORD_Q*PRN_WID*PRN_LEN) ELSE 0 END),0) AS RDY_AJ1800F,	
				
				
			
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='MVJ1624' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q != ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(PRN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS PRN_MVJ1624,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='MVJ1624' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q = ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(FIN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS FIN_MVJ1624,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='MVJ1624' AND ORD_STT_ID IN ('QU','PR','FN','RD') AND ORD_STT_ID NOT IN ('CP') AND ((PRN_CMP_Q=ORD_Q AND FIN_CMP_Q=ORD_Q) OR (ORD_STT_ID = 'RD')) 
				THEN ROUND(ORD_Q*PRN_WID*PRN_LEN) ELSE 0 END),0) AS RDY_MVJ1624,



			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='HPL375' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q != ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(PRN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS PRN_HPL375,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='HPL375' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q = ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(FIN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS FIN_HPL375,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='HPL375' AND ORD_STT_ID IN ('QU','PR','FN','RD') AND ORD_STT_ID NOT IN ('CP') AND ((PRN_CMP_Q=ORD_Q AND FIN_CMP_Q=ORD_Q) OR (ORD_STT_ID = 'RD')) 
				THEN ROUND(ORD_Q*PRN_WID*PRN_LEN) ELSE 0 END),0) AS RDY_HPL375,
				
			
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='SGH6090' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q != ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(PRN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS PRN_SGH6090,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='SGH6090' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q = ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(FIN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS FIN_SGH6090,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='SGH6090' AND ORD_STT_ID IN ('QU','PR','FN','RD') AND ORD_STT_ID NOT IN ('CP') AND ((PRN_CMP_Q=ORD_Q AND FIN_CMP_Q=ORD_Q) OR (ORD_STT_ID = 'RD')) 
				THEN ROUND(ORD_Q*PRN_WID*PRN_LEN) ELSE 0 END),0) AS RDY_SGH6090,
				
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='LQ1390' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q != ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(PRN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS PRN_LQ1390,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='LQ1390' AND ORD_STT_ID IN ('QU','PR','FN') AND PRN_CMP_Q = ORD_Q AND FIN_CMP_Q != ORD_Q 
				THEN (ROUND(ORD_Q*PRN_WID*PRN_LEN) - ROUND(FIN_CMP_Q*PRN_WID*PRN_LEN)) ELSE 0 END),0) AS FIN_LQ1390,
			COALESCE(SUM(CASE WHEN PRN_DIG_EQP='LQ1390' AND ORD_STT_ID IN ('QU','PR','FN','RD') AND ORD_STT_ID NOT IN ('CP') AND ((PRN_CMP_Q=ORD_Q AND FIN_CMP_Q=ORD_Q) OR (ORD_STT_ID = 'RD')) 
				THEN ROUND(ORD_Q*PRN_WID*PRN_LEN) ELSE 0 END),0) AS RDY_LQ1390
				
				
		FROM CMP.PRN_DIG_ORD_DET DET 
			LEFT JOIN CMP.PRN_DIG_ORD_HEAD HED ON DET.ORD_NBR=HED.ORD_NBR 
			LEFT JOIN CMP.PRN_DIG_TYP TYP ON DET.PRN_DIG_TYP=TYP.PRN_DIG_TYP 
		WHERE HED.DEL_NBR=0 
			AND DET.DEL_NBR=0
			AND DATE(HED.ORD_TS) = CURRENT_DATE
			AND DET.PRN_DIG_TYP !='PROD'
	)NOTA";
    $result=mysql_query($query);
	$row=mysql_fetch_array($result);
    $query="SELECT * FROM NST.PARAM_LOC";
    $resultc=mysql_query($query);
    $rowc=mysql_fetch_array($resultc);
    $str=$rowp['FLJ320P'].",".$row['PRN_FLJ320P'].",".$row['FIN_FLJ320P'].",".$row['RDY_FLJ320P'].",".$rowc['PROD_CPCTY_FLJ320P'].";";
    $str.=$rowp['RVS640']. ",".$row['PRN_RVS640']. ",".$row['FIN_RVS640']. ",".$row['RDY_RVS640'].",".$rowc['PROD_CPCTY_RVS640'].";";
    $str.=$rowp['AJ1800F'].",".$row['PRN_AJ1800F'].",".$row['FIN_AJ1800F'].",".$row['RDY_AJ1800F'].",".$rowc['PROD_CPCTY_AJ1800F'].";";
    $str.=$rowp['MVJ1624'].",".$row['PRN_MVJ1624'].",".$row['FIN_MVJ1624'].",".$row['RDY_MVJ1624'].",".$rowc['PROD_CPCTY_MVJ1624'].";";
    $str.=$rowp['HPL375'].",".$row['PRN_HPL375'].",".$row['FIN_HPL375'].",".$row['RDY_HPL375'].",".$rowc['PROD_CPCTY_HPL375'].";";
	$str.=$rowp['SGH6090'].",".$row['PRN_SGH6090'].",".$row['FIN_SGH6090'].",".$row['RDY_SGH6090'].",".$rowc['PROD_CPCTY_SGH6090'].";";
    $str.=$rowp['LQ1390'].",".$row['PRN_LQ1390'].",".$row['FIN_LQ1390'].",".$row['RDY_LQ1390'].",".$rowc['PROD_CPCTY_LQ1390'].";";
	$str.=$rowp['KMC6501']+$rowp['KMC8000_NETT']+$rowp['KMC1085_NETT'].",".$row['PRN_KMC6501'].",".$row['FIN_KMC6501'].",".$row['RDY_KMC6501'].",".$rowc['PROD_CPCTY_KMC6501'].";";

	$result=mysql_query('SELECT * FROM NST.PARAM_LOC;');
	$DefCo=mysql_fetch_array($result);
	$DefCoNbr=$DefCo['CO_NBR_DEF'];
    if($CoNbrDef=='271'){
		$CoEx="'271','1002','1021','4935','5045','5046','5038','5060'";
	}else if($CoNbrDef=='1002'){
		$CoEx="'271','1002','1021','4935','5045','5046','5038','5060'";
	}
    $query="SELECT 
		DATE_FORMAT(CURRENT_DATE,'%e-%c') AS ORD_DTE,
		DATE_FORMAT(CURRENT_DATE,'%e') AS ORD_DAY,
		DATE_FORMAT(CURRENT_DATE,'%c') AS ORD_MONTH,
		DATE_FORMAT(CURRENT_DATE,'%Y') AS ORD_YEAR,
		COALESCE((SELECT (SUM(COALESCE(TOT_SUB,0)+COALESCE(TOT_SUB_ADD,0))+MAX(COALESCE(HED.FEE_MISC,0))) AS REVENUE
	FROM CMP.PRN_DIG_ORD_HEAD HED 
		LEFT OUTER JOIN CMP.PRN_DIG_ORD_DET DET ON HED.ORD_NBR=DET.ORD_NBR 
		LEFT OUTER JOIN(
			SELECT 
				ORD_DET_NBR,
				SUM(TOT_SUB) AS TOT_SUB_ADD 
			FROM CMP.PRN_DIG_ORD_VAL_ADD
			WHERE DATE(CRT_TS) = CURRENT_DATE
			GROUP BY ORD_NBR) 
		VAL ON DET.ORD_DET_NBR=VAL.ORD_DET_NBR 
	WHERE HED.DEL_NBR=0 AND DET.DEL_NBR=0 AND DET.PRN_DIG_TYP !='PROD' AND (BUY_CO_NBR IS NULL OR BUY_CO_NBR NOT IN ($CoEx)) AND DATE(ORD_TS) = CURRENT_DATE) ,0) REVENUE,CURRENT_DATE AS DTE
	ORDER BY DTE";
    $result=mysql_query($query);
	$row=mysql_fetch_array($result);
    $str.=$row['REVENUE'].";";
    $query="SELECT 
		FLEX_BASE_Q,
		DOC_BASE_Q,
		BASE_PCT,
		FLEX_INC_Q,
		DOC_INC_Q,
		FLEX_INC_PCT,
		DOC_INC_PCT,
		BEG_DT,
		END_DT
	FROM CMP.PRN_DIG_BON_PLAN
	WHERE BEG_DT<=CURRENT_DATE AND END_DT>=CURRENT_DATE";
    //echo $query;
    $result=mysql_query($query);
    $row=mysql_fetch_array($result);
    $str.=$row['FLEX_BASE_Q'].",".$row['FLEX_INC_Q'].",".$row['BASE_PCT'].",".$row['FLEX_INC_PCT'].";";
	$str.=$row['DOC_BASE_Q'] .",".$row['DOC_INC_Q'] .",".$row['BASE_PCT'].",".$row['DOC_INC_PCT'].";";
	$query="SELECT 
		DATE_FORMAT(DTE,'%e-%c') AS ORD_DTE,
		DATE_FORMAT(DTE,'%e') AS ORD_DAY,
		DATE_FORMAT(DTE,'%c') AS ORD_MONTH,
		DATE_FORMAT(DTE,'%Y') AS ORD_YEAR,
		REV,
		FLJ320P,
		KMC6501,
		RVS640,
		AJ1800F,
		MVJ1624,
		HPL375,
		SGH6090,
		LQ1390,
		DTE
	FROM CDW.PRN_DIG_DSH_BRD 
	WHERE DTE BETWEEN (CURRENT_DATE - INTERVAL 4 WEEK) AND CURRENT_DATE";
    $result=mysql_query($query);
	while($row=mysql_fetch_array($result)){
		$revs[]=$row['REV'];
		$vols[0][]=$row['FLJ320P'];
		$vols[1][]=$row['KMC6501'];
		$vols[2][]=$row['RVS640'];
		$vols[3][]=$row['AJ1800F'];
		$vols[4][]=$row['MVJ1624'];
		$vols[5][]=$row['HPL375'];
		$vols[6][]=$row['SGH6090'];
		$vols[7][]=$row['LQ1390'];
		$dtes[]=$row['DTE'];
	}
	foreach($dtes as $dte){
		$str.=$dte.",";
	}
	$str=substr($str,0,strlen($str)-1);$str.=";";
	foreach($revs as $rev){
		$str.=$rev.",";
	}
	$str=substr($str,0,strlen($str)-1);$str.=";";
	foreach($vols as $vol){
		foreach($vol as $eVol){
			$str.=$eVol.",";
		}
		$str=substr($str,0,strlen($str)-1);$str.=";";
	}
	$str=substr($str,0,strlen($str)-1);$str.=";";
    //echo ($str);
    echo simple_crypt($str);
?>
