<?php 
include "framework/database/connect.php";
include "framework/functions/default.php";
include "framework/functions/crypt.php";
include "framework/functions/print-digital.php";

$n 			= (14 * 7);
$date		= mktime(0 , 0 , 0 , date("m"), date("d") - $n, date("Y"));
$beginDate	= date('Y-m-d', $date);

//Creative Hub
$queryHub = "SELECT
	COALESCE(SUM(DET.TOT_SUB),0) AS REVENUE
FROM CMP.RTL_ORD_DET DET
	LEFT OUTER JOIN CMP.RTL_ORD_HEAD HED ON DET.ORD_NBR = HED.ORD_NBR
WHERE DATE(ORD_BEG_TS) = CURRENT_DATE AND HED.DEL_NBR = 0 AND DET.DEL_NBR = 0
GROUP BY DATE(ORD_BEG_TS)";
$resultHub 	= mysql_query($queryHub);
$rowHub		= mysql_fetch_array($resultHub);
$str		= $rowHub['REVENUE'].";";

$queryDayHub = "SELECT 
	TGL.Date, 
	(CASE WHEN RPT.ORD_DTE IS NULL THEN YEAR(TGL.Date) ELSE RPT.ORD_DTE END) AS DTE,
	(CASE WHEN RPT.ORD_DTE IS NULL THEN CONCAT(MONTH(TGL.Date),'-',DAY(TGL.Date)) ELSE RPT.ORD_DTE END) AS ORD_DTE,
	(CASE WHEN RPT.ORD_DAY IS NULL THEN DAY(TGL.Date) ELSE RPT.ORD_DAY END) AS ORD_DAY,
	(CASE WHEN RPT.ORD_MONTH IS NULL THEN MONTH(TGL.Date) ELSE RPT.ORD_MONTH END) AS ORD_MONTH,
	(CASE WHEN RPT.ORD_YEAR IS NULL THEN YEAR(TGL.Date) ELSE RPT.ORD_YEAR END) AS ORD_YEAR,
	COALESCE(RPT.REVENUE,0) AS REVENUE,
	COALESCE(PYMT.TND_AMT,0) AS OMZET
FROM(
	SELECT '".$beginDate."' + INTERVAL (A.A + (10 * B.A) + (100 * C.A)) DAY AS DATE
	FROM (SELECT 0 AS A UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS A
	CROSS JOIN (SELECT 0 AS A UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS B
	CROSS JOIN (SELECT 0 AS A UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS C
) TGL
LEFT OUTER JOIN (
	SELECT
		DATE_FORMAT(HED.ORD_BEG_TS,'%e-%c') AS ORD_DTE,
		DATE_FORMAT(HED.ORD_BEG_TS,'%e') AS ORD_DAY,
		DATE_FORMAT(HED.ORD_BEG_TS,'%c') AS ORD_MONTH,
		DATE_FORMAT(HED.ORD_BEG_TS,'%Y') AS ORD_YEAR,
		SUM(DET.TOT_SUB) AS REVENUE,
		DATE(HED.ORD_BEG_TS) AS DTE
	FROM CMP.RTL_ORD_DET DET
		LEFT OUTER JOIN CMP.RTL_ORD_HEAD HED ON DET.ORD_NBR = HED.ORD_NBR
	WHERE ORD_BEG_TS BETWEEN (CURRENT_DATE - INTERVAL 14 WEEK) AND CURRENT_DATE 
		AND HED.DEL_NBR = 0
		AND DET.DEL_NBR = 0
	GROUP BY DATE(ORD_BEG_TS)
) RPT ON TGL.Date = RPT.DTE
	LEFT OUTER JOIN(
		SELECT 
			PYM.ORD_NBR,
			SUM(PYM.TND_AMT) / 1000000 AS TND_AMT,
			DATE(CRT_TS) AS CRT_DTE
		FROM CMP.RTL_ORD_PYMT PYM
		WHERE PYM.DEL_NBR = 0 
		GROUP BY DATE(CRT_TS)
	)PYMT ON TGL.Date = PYMT.CRT_DTE
WHERE TGL.Date BETWEEN (CURRENT_DATE - INTERVAL 4 WEEK) AND CURRENT_DATE";
//echo "<pre>".$query;
$resultDayHub = mysql_query($queryDayHub);
while($rowDayHub=mysql_fetch_array($resultDayHub)){
	$revDayHub[]=$rowDayHub['REVENUE'];
	$dteDayHub[]=$rowDayHub['Date'];
}

foreach($dteDayHub as $dteDaysHub){
	$str.=$dteDaysHub.",";
}
$str=substr($str,0,strlen($str)-1);$str.=";";

foreach($revDayHub as $revDaysHub){
	$str.=$revDaysHub.",";
}
$str=substr($str,0,strlen($str)-1);$str.=";";

//Kopi Tugu
$queryKopi = "SELECT
	COALESCE(RPT.REVENUE,0) - COALESCE(RPT.DISC_FLO_AMT,0) AS REVENUE
FROM (
	SELECT 
		SUM(CASE 
			WHEN CSH.CSH_FLO_TYP = 'RT' THEN CSH.TND_AMT - COALESCE((TTL.DISC_PCT_AMT + TTL.DISC_AMT), 0) 
			WHEN CSH.CSH_FLO_TYP = 'FL' THEN CSH.TND_AMT
			ELSE 0 END) 
		AS REVENUE,
		SUM(CASE WHEN CSH.CSH_FLO_TYP = 'DS' THEN CSH.TND_AMT ELSE 0 END) AS DISC_FLO_AMT,
		DATE(CRT_TS) AS DTE,
		CSH.CSH_FLO_TYP
	FROM RTL.CSH_REG CSH
		LEFT JOIN( 
			SELECT 
				REG_NBR,
				COALESCE(CASE WHEN CSH_FLO_TYP IN ('RT', 'FL') THEN DISC_PCT ELSE 0 END, 0) AS DISC_PCT, 
				COALESCE(CASE WHEN CSH_FLO_TYP IN ('RT', 'FL') THEN (DISC_PCT/100)*TND_AMT ELSE 0 END, 0) AS DISC_PCT_AMT, 
				COALESCE(CASE WHEN CSH_FLO_TYP IN ('RT', 'FL') THEN DISC_AMT ELSE 0 END, 0) AS DISC_AMT
			FROM RTL.CSH_REG
			WHERE POS_ID=3 AND ACT_F = 0 AND DATE(CRT_TS) = CURRENT_DATE
		) TTL ON TTL.REG_NBR = CSH.REG_NBR
	WHERE CSH.ACT_F = 0 AND CSH.CSH_FLO_TYP IN ('RT','DS') AND CSH.POS_ID = 3 AND DATE(CRT_TS) = CURRENT_DATE
	GROUP BY DATE(CRT_TS)
) RPT";
$resultKopi = mysql_query($queryKopi);
$rowKopi = mysql_fetch_array($resultKopi);
$str	.= $rowKopi['REVENUE'].";";

$query = "SELECT 
	TGL.Date, 
	(CASE WHEN RPT.ORD_DTE IS NULL THEN YEAR(TGL.Date) ELSE RPT.ORD_DTE END) AS DTE,
	(CASE WHEN RPT.ORD_DTE IS NULL THEN CONCAT(MONTH(TGL.Date),'-',DAY(TGL.Date)) ELSE RPT.ORD_DTE END) AS ORD_DTE,
	(CASE WHEN RPT.ORD_DAY IS NULL THEN DAY(TGL.Date) ELSE RPT.ORD_DAY END) AS ORD_DAY,
	(CASE WHEN RPT.ORD_MONTH IS NULL THEN MONTH(TGL.Date) ELSE RPT.ORD_MONTH END) AS ORD_MONTH,
	(CASE WHEN RPT.ORD_YEAR IS NULL THEN YEAR(TGL.Date) ELSE RPT.ORD_YEAR END) AS ORD_YEAR,
	COALESCE(RPT.REVENUE,0) - COALESCE(RPT.DISC_FLO_AMT,0) AS REV,
	COALESCE(RPT.DISC_FLO_AMT,0) AS DISC_FLO_AMT,
	COALESCE(RPT.CSH_FLO_TYP, 'RT') AS CSH_FLO_TYP
FROM(
	SELECT '" . $beginDate . "' + INTERVAL (a.a + (10 * b.a) + (100 * c.a)) DAY AS DATE
	FROM (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS a 
	CROSS JOIN (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS b
	CROSS JOIN (SELECT 0 AS a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS c
	) TGL
LEFT OUTER JOIN (
	SELECT 
		DATE_FORMAT(CRT_TS,'%e-%c') AS ORD_DTE,
		DATE_FORMAT(CRT_TS,'%e') AS ORD_DAY,
		DATE_FORMAT(CRT_TS,'%c') AS ORD_MONTH,
		DATE_FORMAT(CRT_TS,'%Y') AS ORD_YEAR,
		SUM(CASE 
			WHEN CSH.CSH_FLO_TYP = 'RT' THEN CSH.TND_AMT - COALESCE((TTL.DISC_PCT_AMT + TTL.DISC_AMT), 0) 
			WHEN CSH.CSH_FLO_TYP = 'FL' THEN CSH.TND_AMT
			ELSE 0 END) 
		AS REVENUE,
		SUM(CASE WHEN CSH.CSH_FLO_TYP = 'DS' THEN CSH.TND_AMT ELSE 0 END) AS DISC_FLO_AMT,
		DATE(CRT_TS) AS DTE,
		CSH.CSH_FLO_TYP
	FROM RTL.CSH_REG CSH
		LEFT JOIN( 
			SELECT 
				REG_NBR,
				COALESCE(CASE WHEN CSH_FLO_TYP IN ('RT', 'FL') THEN DISC_PCT ELSE 0 END, 0) AS DISC_PCT, 
				COALESCE(CASE WHEN CSH_FLO_TYP IN ('RT', 'FL') THEN (DISC_PCT/100)*TND_AMT ELSE 0 END, 0) AS DISC_PCT_AMT, 
				COALESCE(CASE WHEN CSH_FLO_TYP IN ('RT', 'FL') THEN DISC_AMT ELSE 0 END, 0) AS DISC_AMT
			FROM RTL.CSH_REG
			WHERE POS_ID = 3 AND ACT_F = 0
		) TTL ON TTL.REG_NBR = CSH.REG_NBR
	WHERE CSH.ACT_F = 0 AND CSH.CSH_FLO_TYP IN ('RT','DS') AND CSH.POS_ID = 3
	GROUP BY DATE(CRT_TS)
	ORDER BY DATE(CRT_TS)
) RPT ON TGL.Date = RPT.DTE
WHERE TGL.Date BETWEEN (CURRENT_DATE - INTERVAL 4 WEEK) AND CURRENT_DATE
ORDER BY TGL.Date ASC";
//echo "<pre>".$query;
$result = mysql_query($query);
while($row=mysql_fetch_array($result)){
	$revs[]=$row['REV'];
	$dtes[]=$row['Date'];
}

foreach($dtes as $dte){
	$str.=$dte.",";
}
$str=substr($str,0,strlen($str)-1);$str.=";";

foreach($revs as $rev){
	$str.=$rev.",";
}
$str=substr($str,0,strlen($str)-1);$str.=";";

//echo "<pre>".$str;
echo simple_crypt($str);
?>