SELECT 
	STK.ORD_DTE,
	STK.ORD_YEAR,
	STK.ORD_MONTH,
	STK.ORD_DAY,
	STK.ORD_MONTHNAME,
	STK.ORD_DET_NBR,
	STK.ORD_NBR,
	STK.INV_NBR,
	STK.INV_NAME,
	STK.CAT_NBR,
	STK.CAT_DESC,
	STK.CAT_SUB_NBR,
	STK.CAT_SUB_DESC,
	STK.PRN_DIG_TYP,
	STK.PRN_DIG_EQP,
	STK.PRN_DIG_EQP_DESC,
	STK.PRN_DIG_DESC,
	SUM(COALESCE(STK.RCV_Q,0)) AS RCV_Q,
	SUM(COALESCE(STK.XF_IN_Q,0)) AS XF_IN_Q,
	SUM(COALESCE(STK.RTR_Q,0)) AS RTR_Q,
	SUM(COALESCE(STK.XF_OUT_Q,0)) AS XF_OUT_Q,
	SUM(COALESCE(STK.COR_Q,0)) AS COR_Q,
	SUM(COALESCE(MOV.MOV_Q,0)) AS MOV_Q,
	SUM(COALESCE(STK.RCV_TOT_SUB,0)) AS RCV_TOT_SUB,
	SUM(COALESCE(STK.RTR_TOT_SUB,0)) AS RTR_TOT_SUB,
	SUM(COALESCE(STK.COR_TOT_SUB,0)) AS COR_TOT_SUB,
	SUM(COALESCE(MOV.MOV_TOT_SUB,0)) AS MOV_TOT_SUB,
	SUM(COALESCE(STK.XF_OUT_TOT_SUB,0)) AS XF_OUT_TOT_SUB,
	SUM(COALESCE(STK.RCV_Q,0) + COALESCE(STK.XF_IN_Q,0) - COALESCE(STK.RTR_Q,0) + COALESCE(STK.COR_Q,0) - COALESCE(STK.XF_OUT_Q,0) - COALESCE(MOV.MOV_Q,0)) AS BALANCE_Q,
	SUM(COALESCE(STK.RCV_TOT_SUB,0) + COALESCE(STK.XF_IN_TOT_SUB,0) - COALESCE(STK.RTR_TOT_SUB,0) + COALESCE(STK.COR_TOT_SUB,0) - COALESCE(STK.XF_OUT_TOT_SUB,0) - COALESCE(MOV.MOV_TOT_SUB,0)) AS BALANCE_AMT
FROM (SELECT
			DATE(HED.DL_TS) AS ORD_DTE,
			YEAR(HED.DL_TS) AS ORD_YEAR,
			MONTH(HED.DL_TS) AS ORD_MONTH,
			DAY(HED.DL_TS) AS ORD_DAY,
			MONTHNAME(HED.DL_TS) AS ORD_MONTHNAME,
			EQP.PRN_DIG_EQP,
			EQP.PRN_DIG_EQP_DESC,
			DET.ORD_DET_NBR,
			DET.INV_NBR,
			INV.NAME AS INV_NAME,
			HED.ORD_NBR, 
			CAT.CAT_NBR,
			CAT.CAT_DESC,
			SUB.CAT_SUB_NBR,
			SUB.CAT_SUB_DESC,
			TYP.PRN_DIG_TYP,
			TYP.PRN_DIG_DESC,
			SUM(CASE WHEN HED.IVC_TYP = 'RC' AND HED.RCV_CO_NBR =  THEN DET.ORD_Q ELSE 0 END) AS RCV_Q,
			SUM(CASE WHEN HED.IVC_TYP = 'XF' AND HED.RCV_CO_NBR =  THEN DET.ORD_Q ELSE 0 END) AS XF_IN_Q,
			SUM(CASE WHEN HED.IVC_TYP = 'RT' AND HED.SHP_CO_NBR =  THEN DET.ORD_Q ELSE 0 END) AS RTR_Q,
			SUM(CASE WHEN HED.IVC_TYP = 'CR' THEN DET.ORD_Q ELSE 0 END) AS COR_Q,
			SUM(CASE WHEN HED.IVC_TYP = 'XF' AND HED.SHP_CO_NBR =  THEN DET.ORD_Q ELSE 0 END) AS XF_OUT_Q,
			SUM(CASE WHEN HED.IVC_TYP = 'RC' AND HED.RCV_CO_NBR =  THEN DET.TOT_SUB ELSE 0 END) AS RCV_TOT_SUB,
			SUM(CASE WHEN HED.IVC_TYP = 'XF' AND HED.RCV_CO_NBR =  THEN DET.TOT_SUB ELSE 0 END) AS XF_IN_TOT_SUB,
			SUM(CASE WHEN HED.IVC_TYP = 'RT' AND HED.SHP_CO_NBR =  THEN DET.TOT_SUB ELSE 0 END) AS RTR_TOT_SUB,
			SUM(CASE WHEN HED.IVC_TYP = 'CR' THEN DET.TOT_SUB ELSE 0 END) AS COR_TOT_SUB,
			SUM(CASE WHEN HED.IVC_TYP = 'XF' AND HED.SHP_CO_NBR =  THEN DET.TOT_SUB ELSE 0 END) AS XF_OUT_TOT_SUB
		FROM RTL.RTL_STK_DET DET
		INNER JOIN RTL.RTL_STK_HEAD HED
			ON DET.ORD_NBR = HED.ORD_NBR
		INNER JOIN RTL.INVENTORY INV
			ON DET.INV_NBR = INV.INV_NBR
		LEFT JOIN CMP.PRN_DIG_TYP TYP
			ON INV.PRD_PRC_TYP = TYP.PRN_DIG_TYP
		LEFT JOIN CMP.PRN_DIG_EQP EQP
			ON EQP.PRN_DIG_EQP = TYP.PRN_DIG_EQP
		INNER JOIN RTL.CAT_SUB SUB
			ON HED.CAT_SUB_NBR = SUB.CAT_SUB_NBR
		INNER JOIN RTL.CAT CAT
			ON CAT.CAT_NBR = SUB.CAT_NBR
		INNER JOIN CMP.COMPANY SPL
			ON SPL.CO_NBR = HED.SHP_CO_NBR
		INNER JOIN CMP.COMPANY RCV
			ON RCV.CO_NBR = HED.RCV_CO_NBR
		INNER JOIN RTL.CAT_TYP TYP 
			ON TYP.CAT_TYP_NBR = SUB.CAT_TYP_NBR
		WHERE HED.DEL_F=0 
			AND DATE(HED.DL_TS) >= (SELECT BEG_ACCTG FROM NST.PARAM_LOC) 
			AND DATE(HED.DL_TS) <= '2017-04-21' 
			AND (HED.IVC_TYP = 'RC' OR HED.IVC_TYP = 'RT' OR HED.IVC_TYP = 'XF' OR HED.IVC_TYP = 'CR') 
			AND HED.TOT_REM = 0
		GROUP BY DET.ORD_DET_NBR
) STK
LEFT JOIN
(SELECT MOV.ORD_DET_NBR,
	SUM(COALESCE(MOV.MOV_Q,0)) AS MOV_Q,
	SUM(COALESCE(MOV.MOV_Q * MOV.DET_INV_PRC,0)) AS MOV_TOT_SUB
FROM RTL.INV_MOV MOV
	JOIN RTL.RTL_STK_DET DET 
		ON MOV.ORD_DET_NBR = DET.ORD_DET_NBR
	LEFT JOIN RTL.RTL_STK_HEAD HED
		ON DET.ORD_NBR = HED.ORD_NBR
	LEFT JOIN RTL.INVENTORY INV
		ON DET.INV_NBR = INV.INV_NBR
	LEFT JOIN CMP.PRN_DIG_TYP TYP
		ON INV.PRD_PRC_TYP = TYP.PRN_DIG_TYP
	LEFT JOIN RTL.CAT_SUB SUB
		ON INV.CAT_SUB_NBR = SUB.CAT_SUB_NBR
	LEFT JOIN RTL.CAT CAT
		ON CAT.CAT_NBR = SUB.CAT_NBR
	LEFT JOIN CMP.COMPANY SPL
		ON SPL.CO_NBR = HED.SHP_CO_NBR
	LEFT JOIN CMP.COMPANY RCV
		ON RCV.CO_NBR = HED.RCV_CO_NBR
	LEFT JOIN CMP.PRN_DIG_EQP EQP
			ON EQP.PRN_DIG_EQP = TYP.PRN_DIG_EQP
	WHERE HED.DEL_F=0 AND INV.CAT_NBR IN (1,10) AND INV.CAT_SUB_NBR != '202' AND MOV.DEL_NBR = 0 AND DATE(MOV.CRT_TS) >= (SELECT BEG_ACCTG FROM NST.PARAM_LOC) AND DATE(HED.DL_TS) >= (SELECT BEG_ACCTG FROM NST.PARAM_LOC) AND (DATE(HED.DL_TS) <= '2017-04-21' AND DATE(MOV.CRT_TS) <= '2017-04-21') AND (HED.IVC_TYP = 'RC' OR HED.IVC_TYP = 'XF')
	GROUP BY MOV.ORD_DET_NBR
) MOV ON MOV.ORD_DET_NBR = STK.ORD_DET_NBR

GROUP BY STK.PRN_DIG_TYP
ORDER BY STK.PRN_DIG_TYP DESC